//
//  SignUp_7Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 23/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_7PresentationLogic
{
  func presentSomething(response: SignUp_7.Something.Response)
}

class SignUp_7Presenter: SignUp_7PresentationLogic
{
  weak var viewController: SignUp_7DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignUp_7.Something.Response)
  {
    let viewModel = SignUp_7.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
