//
//  SignUp_7Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 23/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_7BusinessLogic
{
  func doSomething(request: SignUp_7.Something.Request)
}

protocol SignUp_7DataStore
{
  //var name: String { get set }
}

class SignUp_7Interactor: SignUp_7BusinessLogic, SignUp_7DataStore
{
  var presenter: SignUp_7PresentationLogic?
  var worker: SignUp_7Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignUp_7.Something.Request)
  {
    worker = SignUp_7Worker()
    worker?.doSomeWork()
    
    let response = SignUp_7.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
