//
//  SignUp_7ViewController.swift
//  LoginFlowApp
//
//  Created by Thanos on 23/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import XLPagerTabStrip

protocol SignUp_7DisplayLogic: class
{
  func displaySomething(viewModel: SignUp_7.Something.ViewModel)
}

class SignUp_7ViewController: UIViewController, SignUp_7DisplayLogic
{
  var interactor: SignUp_7BusinessLogic?
  var router: (NSObjectProtocol & SignUp_7RoutingLogic & SignUp_7DataPassing)?
    
    @IBOutlet weak var signUpView: UIView!
    @IBOutlet weak var createAnAccount: UIButton!
    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SignUp_7Interactor()
    let presenter = SignUp_7Presenter()
    let router = SignUp_7Router()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    self.view.backgroundColor = UIColor.appBackground
    createAnAccount.backgroundColor = UIColor.appRed
    signUpView.layer.shadowColor = UIColor.lightGray.cgColor
    signUpView.layer.shadowOpacity = 1.0
    signUpView.layer.shadowOffset = CGSize(width: 1, height: 1)
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = SignUp_7.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: SignUp_7.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
    
    
    
}

extension SignUp_7ViewController: IndicatorInfoProvider{
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return IndicatorInfo(title: "SIGN UP")
    }
    
    
}
