//
//  VerifyYourAccount24Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 08/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VerifyYourAccount24PresentationLogic
{
  func presentSomething(response: VerifyYourAccount24.Something.Response)
}

class VerifyYourAccount24Presenter: VerifyYourAccount24PresentationLogic
{
  weak var viewController: VerifyYourAccount24DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: VerifyYourAccount24.Something.Response)
  {
    let viewModel = VerifyYourAccount24.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
