//
//  VerifyYourAccount24Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 08/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VerifyYourAccount24BusinessLogic
{
  func doSomething(request: VerifyYourAccount24.Something.Request)
}

protocol VerifyYourAccount24DataStore
{
  //var name: String { get set }
}

class VerifyYourAccount24Interactor: VerifyYourAccount24BusinessLogic, VerifyYourAccount24DataStore
{
  var presenter: VerifyYourAccount24PresentationLogic?
  var worker: VerifyYourAccount24Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: VerifyYourAccount24.Something.Request)
  {
    worker = VerifyYourAccount24Worker()
    worker?.doSomeWork()
    
    let response = VerifyYourAccount24.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
