//
//  VerifyYourAccount24Router.swift
//  LoginFlowApp
//
//  Created by Thanos on 08/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol VerifyYourAccount24RoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol VerifyYourAccount24DataPassing
{
  var dataStore: VerifyYourAccount24DataStore? { get }
}

class VerifyYourAccount24Router: NSObject, VerifyYourAccount24RoutingLogic, VerifyYourAccount24DataPassing
{
  weak var viewController: VerifyYourAccount24ViewController?
  var dataStore: VerifyYourAccount24DataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: VerifyYourAccount24ViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: VerifyYourAccount24DataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
