//
//  Login_6Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 23/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Login_6BusinessLogic
{
  func doSomething(request: Login_6.Something.Request)
}

protocol Login_6DataStore
{
  //var name: String { get set }
}

class Login_6Interactor: Login_6BusinessLogic, Login_6DataStore
{
  var presenter: Login_6PresentationLogic?
  var worker: Login_6Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Login_6.Something.Request)
  {
    worker = Login_6Worker()
    worker?.doSomeWork()
    
    let response = Login_6.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
