//
//  Login_6Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 23/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Login_6PresentationLogic
{
  func presentSomething(response: Login_6.Something.Response)
}

class Login_6Presenter: Login_6PresentationLogic
{
  weak var viewController: Login_6DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Login_6.Something.Response)
  {
    let viewModel = Login_6.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
