//
//  Login_5Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 21/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Login_5BusinessLogic
{
  func doSomething(request: Login_5.Something.Request)
}

protocol Login_5DataStore
{
  //var name: String { get set }
}

class Login_5Interactor: Login_5BusinessLogic, Login_5DataStore
{
  var presenter: Login_5PresentationLogic?
  var worker: Login_5Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Login_5.Something.Request)
  {
    worker = Login_5Worker()
    worker?.doSomeWork()
    
    let response = Login_5.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
