//
//  Login_5Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 21/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Login_5PresentationLogic
{
  func presentSomething(response: Login_5.Something.Response)
}

class Login_5Presenter: Login_5PresentationLogic
{
  weak var viewController: Login_5DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Login_5.Something.Response)
  {
    let viewModel = Login_5.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
