//
//  SignUp_2Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 20/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_2BusinessLogic
{
  func doSomething(request: SignUp_2.Something.Request)
}

protocol SignUp_2DataStore
{
  //var name: String { get set }
}

class SignUp_2Interactor: SignUp_2BusinessLogic, SignUp_2DataStore
{
  var presenter: SignUp_2PresentationLogic?
  var worker: SignUp_2Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignUp_2.Something.Request)
  {
    worker = SignUp_2Worker()
    worker?.doSomeWork()
    
    let response = SignUp_2.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
