//
//  SignUp_2Worker.swift
//  LoginFlowApp
//
//  Created by Thanos on 20/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SignUp_2Worker
{
  func doSomeWork()
  {
  }
}
