//
//  SignUp_2ViewController.swift
//  LoginFlowApp
//
//  Created by Thanos on 20/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_2DisplayLogic: class
{
  func displaySomething(viewModel: SignUp_2.Something.ViewModel)
}

class SignUp_2ViewController: UIViewController, SignUp_2DisplayLogic
{
  var interactor: SignUp_2BusinessLogic?
  var router: (NSObjectProtocol & SignUp_2RoutingLogic & SignUp_2DataPassing)?

    @IBOutlet weak var logoImageView: UIImageView!
    @IBOutlet weak var signUpButton: UIButton!
    
    override var preferredStatusBarStyle: UIStatusBarStyle{
        return .lightContent
    }
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SignUp_2Interactor()
    let presenter = SignUp_2Presenter()
    let router = SignUp_2Router()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    logoImageView.layer.cornerRadius = logoImageView.frame.width/2
    signUpButton.backgroundColor = .appRed
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = SignUp_2.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: SignUp_2.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
    @IBAction func signUpButtonTapped(_ sender: Any) {
    }
    
}
