//
//  Login22Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 07/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Login22BusinessLogic
{
  func doSomething(request: Login22.Something.Request)
}

protocol Login22DataStore
{
  //var name: String { get set }
}

class Login22Interactor: Login22BusinessLogic, Login22DataStore
{
  var presenter: Login22PresentationLogic?
  var worker: Login22Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Login22.Something.Request)
  {
    worker = Login22Worker()
    worker?.doSomeWork()
    
    let response = Login22.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
