//
//  Login22Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 07/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Login22PresentationLogic
{
  func presentSomething(response: Login22.Something.Response)
}

class Login22Presenter: Login22PresentationLogic
{
  weak var viewController: Login22DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Login22.Something.Response)
  {
    let viewModel = Login22.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
