//
//  SignUp_9Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 27/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_9PresentationLogic
{
  func presentSomething(response: SignUp_9.Something.Response)
}

class SignUp_9Presenter: SignUp_9PresentationLogic
{
  weak var viewController: SignUp_9DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignUp_9.Something.Response)
  {
    let viewModel = SignUp_9.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
