//
//  SignUp_9Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 27/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_9BusinessLogic
{
  func doSomething(request: SignUp_9.Something.Request)
}

protocol SignUp_9DataStore
{
  //var name: String { get set }
}

class SignUp_9Interactor: SignUp_9BusinessLogic, SignUp_9DataStore
{
  var presenter: SignUp_9PresentationLogic?
  var worker: SignUp_9Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignUp_9.Something.Request)
  {
    worker = SignUp_9Worker()
    worker?.doSomeWork()
    
    let response = SignUp_9.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
