//
//  SignUp_8Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 23/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_8BusinessLogic
{
  func doSomething(request: SignUp_8.Something.Request)
}

protocol SignUp_8DataStore
{
  //var name: String { get set }
}

class SignUp_8Interactor: SignUp_8BusinessLogic, SignUp_8DataStore
{
  var presenter: SignUp_8PresentationLogic?
  var worker: SignUp_8Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignUp_8.Something.Request)
  {
    worker = SignUp_8Worker()
    worker?.doSomeWork()
    
    let response = SignUp_8.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
