//
//  SignUp_8ViewController.swift
//  LoginFlowApp
//
//  Created by Thanos on 23/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_8DisplayLogic: class
{
  func displaySomething(viewModel: SignUp_8.Something.ViewModel)
}

class SignUp_8ViewController: UIViewController, SignUp_8DisplayLogic
{
  var interactor: SignUp_8BusinessLogic?
  var router: (NSObjectProtocol & SignUp_8RoutingLogic & SignUp_8DataPassing)?

    @IBOutlet weak var uploadImageButton: UIButton!
    @IBOutlet weak var signUpDetailsView: UIView!
    @IBOutlet weak var createAnAccountBtn: UIButton!
    override var preferredStatusBarStyle: UIStatusBarStyle{
        return .lightContent
    }
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SignUp_8Interactor()
    let presenter = SignUp_8Presenter()
    let router = SignUp_8Router()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    if self.revealViewController() != nil {
        self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
    }
    self.navigationController?.navigationBar.setBackgroundImage(UIImage(), for: .default)
    self.navigationController?.navigationBar.shadowImage = UIImage()
    self.navigationController?.navigationBar.barTintColor = UIColor.appRed
    self.view.backgroundColor = UIColor.appRed
    UIApplication.shared.statusBarView?.backgroundColor = UIColor.appStatusBarRed
    uploadImageButton.layer.cornerRadius = uploadImageButton.frame.width/2
    signUpDetailsView.layer.shadowColor = UIColor.lightGray.cgColor
    signUpDetailsView.layer.shadowOpacity = 1
    signUpDetailsView.layer.shadowOffset = CGSize(width: 0, height: 1)
    createAnAccountBtn.backgroundColor = .appRed
    doSomething()
  }
    
    override func viewDidAppear(_ animated: Bool) {
        navigationController?.navigationBar.barStyle = .black
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = SignUp_8.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: SignUp_8.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
