//
//  LoginFlow_1ViewController.swift
//  LoginFlowApp
//
//  Created by Thanos on 19/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SWRevealViewController

protocol SignUp_1DisplayLogic: class
{
  func displaySomething(viewModel: SignUp_1.Something.ViewModel)
}

class SignUp_1ViewController: UIViewController, SignUp_1DisplayLogic
{
    @IBOutlet weak var logoImageView: UIImageView!
    @IBOutlet weak var createAccButton: UIButton!
    
    @IBAction func menuButton(_ sender: Any) {
    }
    @IBOutlet weak var menuButton: UIBarButtonItem!
    var interactor: SignUp_1BusinessLogic?
  var router: (NSObjectProtocol & SignUp_1RoutingLogic & SignUp_1DataPassing)?

  override var preferredStatusBarStyle: UIStatusBarStyle{
        return .lightContent
   }
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SignUp_1Interactor()
    let presenter = SignUp_1Presenter()
    let router = SignUp_1Router()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    if self.revealViewController() != nil {
        menuButton.target = self.revealViewController()
        menuButton.action = "revealToggle:"
        self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
    }
    updateUI()
    doSomething()
  }
    
    override func viewDidAppear(_ animated: Bool) {
        navigationController?.navigationBar.barStyle = .black
    }
    
    func updateUI(){
        UIApplication.shared.statusBarView?.backgroundColor = .appStatusBarRed
        setNeedsStatusBarAppearanceUpdate()
        self.navigationController?.navigationBar.barTintColor = .appRed
        logoImageView.layer.cornerRadius = logoImageView.frame.width/2
        createAccButton.backgroundColor = .appStatusBarRed
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = SignUp_1.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: SignUp_1.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
