//
//  LoginFlow_1Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 19/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_1BusinessLogic
{
  func doSomething(request: SignUp_1.Something.Request)
}

protocol SignUp_1DataStore
{
  //var name: String { get set }
}

class SignUp_1Interactor: SignUp_1BusinessLogic, SignUp_1DataStore
{
  var presenter: SignUp_1PresentationLogic?
  var worker: SignUp_1Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignUp_1.Something.Request)
  {
    worker = SignUp_1Worker()
    worker?.doSomeWork()
    
    let response = SignUp_1.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
