//
//  LoginFlow_1Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 19/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_1PresentationLogic
{
  func presentSomething(response: SignUp_1.Something.Response)
}

class SignUp_1Presenter: SignUp_1PresentationLogic
{
  weak var viewController: SignUp_1DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignUp_1.Something.Response)
  {
    let viewModel = SignUp_1.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
