//
//  SignIn_11Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 28/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn_11PresentationLogic
{
  func presentSomething(response: SignIn_11.Something.Response)
}

class SignIn_11Presenter: SignIn_11PresentationLogic
{
  weak var viewController: SignIn_11DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignIn_11.Something.Response)
  {
    let viewModel = SignIn_11.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
