//
//  Log21Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 06/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Log21BusinessLogic
{
  func doSomething(request: Log21.Something.Request)
}

protocol Log21DataStore
{
  //var name: String { get set }
}

class Log21Interactor: Log21BusinessLogic, Log21DataStore
{
  var presenter: Log21PresentationLogic?
  var worker: Log21Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Log21.Something.Request)
  {
    worker = Log21Worker()
    worker?.doSomeWork()
    
    let response = Log21.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
