//
//  Log21Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 06/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Log21PresentationLogic
{
  func presentSomething(response: Log21.Something.Response)
}

class Log21Presenter: Log21PresentationLogic
{
  weak var viewController: Log21DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Log21.Something.Response)
  {
    let viewModel = Log21.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
