//
//  Log21ViewController.swift
//  LoginFlowApp
//
//  Created by Thanos on 06/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Log21DisplayLogic: class
{
  func displaySomething(viewModel: Log21.Something.ViewModel)
}

class Log21ViewController: UIViewController, Log21DisplayLogic
{
  var interactor: Log21BusinessLogic?
  var router: (NSObjectProtocol & Log21RoutingLogic & Log21DataPassing)?
    override var prefersStatusBarHidden: Bool{
        return true
    }
    @IBOutlet weak var logCollectionView: UICollectionView!
    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = Log21Interactor()
    let presenter = Log21Presenter()
    let router = Log21Router()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    if self.revealViewController() != nil {
        self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
    }
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Log21.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Log21.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}

extension Log21ViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout{
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 2
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
    let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "collSignInCell", for: indexPath) as! LogCollectionViewSignInCell
        
    cell.containerView.layer.shadowColor = UIColor.lightGray.cgColor
    cell.containerView.layer.shadowOffset = CGSize(width: 1, height: 1)
    cell.containerView.layer.shadowOpacity = 1.0
        
    cell.logImageView.layer.cornerRadius = cell.logImageView.frame.width/2
    
    cell.signUpSignInButton.backgroundColor = UIColor.appRed
        
//        if indexPath.row == 0{
//            cell.logImageView.image = UIImage(named: "diamond-on-black")
//            cell.signUpSignInButton.setTitle("Sign In", for: .normal)
//        }
//        else {
//            cell.logImageView.tintColor = UIColor.appBackground
//            cell.logImageView.image = UIImage(named: "user")
//            cell.signUpSignInButton.setTitle("Sign Up", for: .normal)
//        }
        if indexPath.row == 1{
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "collSignUpCell", for: indexPath) as! LogCollectionViewSignUpCell
            
            cell.containerView.layer.shadowColor = UIColor.lightGray.cgColor
            cell.containerView.layer.shadowOffset = CGSize(width: 1, height: 1)
            cell.containerView.layer.shadowOpacity = 1.0
            
            cell.uploadImage.tintColor = UIColor.appBackground
            cell.uploadImage.layer.cornerRadius = cell.uploadImage.frame.width/2
            
            cell.signUpButton.backgroundColor = UIColor.appRed
            
            return cell
        }
        
        
    return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize
    {
        return CGSize(width: self.view.frame.width, height: (UIApplication.shared.keyWindow?.frame.height)!/2)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        return 0
    }
}
