//
//  SignUp_3Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 20/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_3PresentationLogic
{
  func presentSomething(response: SignUp_3.Something.Response)
}

class SignUp_3Presenter: SignUp_3PresentationLogic
{
  weak var viewController: SignUp_3DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignUp_3.Something.Response)
  {
    let viewModel = SignUp_3.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
