//
//  SignUp_3Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 20/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_3BusinessLogic
{
  func doSomething(request: SignUp_3.Something.Request)
}

protocol SignUp_3DataStore
{
  //var name: String { get set }
}

class SignUp_3Interactor: SignUp_3BusinessLogic, SignUp_3DataStore
{
  var presenter: SignUp_3PresentationLogic?
  var worker: SignUp_3Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignUp_3.Something.Request)
  {
    worker = SignUp_3Worker()
    worker?.doSomeWork()
    
    let response = SignUp_3.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
