//
//  SignUp_10Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 28/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_10BusinessLogic
{
  func doSomething(request: SignUp_10.Something.Request)
}

protocol SignUp_10DataStore
{
  //var name: String { get set }
}

class SignUp_10Interactor: SignUp_10BusinessLogic, SignUp_10DataStore
{
  var presenter: SignUp_10PresentationLogic?
  var worker: SignUp_10Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignUp_10.Something.Request)
  {
    worker = SignUp_10Worker()
    worker?.doSomeWork()
    
    let response = SignUp_10.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
