//
//  SignUp_10Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 28/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_10PresentationLogic
{
  func presentSomething(response: SignUp_10.Something.Response)
}

class SignUp_10Presenter: SignUp_10PresentationLogic
{
  weak var viewController: SignUp_10DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignUp_10.Something.Response)
  {
    let viewModel = SignUp_10.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
