# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginFlowApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginFlowApp
  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'SWRevealViewController', '~> 2.3'
end
