//
//  SignIn13Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 02/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn13PresentationLogic
{
  func presentSomething(response: SignIn13.Something.Response)
}

class SignIn13Presenter: SignIn13PresentationLogic
{
  weak var viewController: SignIn13DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignIn13.Something.Response)
  {
    let viewModel = SignIn13.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
