//
//  SignIn13ViewController.swift
//  LoginFlowApp
//
//  Created by Thanos on 02/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn13DisplayLogic: class
{
  func displaySomething(viewModel: SignIn13.Something.ViewModel)
}

class SignIn13ViewController: UIViewController, SignIn13DisplayLogic
{
  var interactor: SignIn13BusinessLogic?
  var router: (NSObjectProtocol & SignIn13RoutingLogic & SignIn13DataPassing)?

    var rememberMe: Bool = false
    override var preferredStatusBarStyle: UIStatusBarStyle{
        return .lightContent
    }
    
    @IBOutlet weak var rememberMeButton: UIButton!
    @IBOutlet weak var signInButton: UIButton!
    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SignIn13Interactor()
    let presenter = SignIn13Presenter()
    let router = SignIn13Router()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    
    if self.revealViewController() != nil {
        self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
    }
    
    setupUI()
    doSomething()
  }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        self.navigationController?.navigationBar.barStyle = .black
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = SignIn13.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: SignIn13.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
    // MARK: Setup UI
    
    func setupUI(){
        signInButton.backgroundColor = UIColor.appRed
        
        self.view.backgroundColor = UIColor.appRed
        
        UIApplication.shared.statusBarView?.backgroundColor = UIColor.clear
    }
    
    // MARK: IBActions
    
    @IBAction func rememberMeTapped(_ sender: UIButton) {
        rememberMe.toggle()
        
        if rememberMe{
            rememberMeButton.setImage(UIImage(named: "checked_box_app_background"), for: .normal)
        }
        else{
            rememberMeButton.setImage(UIImage(named: "unchecked_app_background"), for: .normal)
        }
    }
    
}
