//
//  SignIn13Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 02/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn13BusinessLogic
{
  func doSomething(request: SignIn13.Something.Request)
}

protocol SignIn13DataStore
{
  //var name: String { get set }
}

class SignIn13Interactor: SignIn13BusinessLogic, SignIn13DataStore
{
  var presenter: SignIn13PresentationLogic?
  var worker: SignIn13Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignIn13.Something.Request)
  {
    worker = SignIn13Worker()
    worker?.doSomeWork()
    
    let response = SignIn13.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
