//
//  SignIn19Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 06/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn19PresentationLogic
{
  func presentSomething(response: SignIn19.Something.Response)
}

class SignIn19Presenter: SignIn19PresentationLogic
{
  weak var viewController: SignIn19DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignIn19.Something.Response)
  {
    let viewModel = SignIn19.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
