//
//  SignIn19Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 06/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn19BusinessLogic
{
  func doSomething(request: SignIn19.Something.Request)
}

protocol SignIn19DataStore
{
  //var name: String { get set }
}

class SignIn19Interactor: SignIn19BusinessLogic, SignIn19DataStore
{
  var presenter: SignIn19PresentationLogic?
  var worker: SignIn19Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignIn19.Something.Request)
  {
    worker = SignIn19Worker()
    worker?.doSomeWork()
    
    let response = SignIn19.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
