//
//  SignIn19ViewController.swift
//  LoginFlowApp
//
//  Created by Thanos on 06/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn19DisplayLogic: class
{
  func displaySomething(viewModel: SignIn19.Something.ViewModel)
}

class SignIn19ViewController: UIViewController, SignIn19DisplayLogic
{
  var interactor: SignIn19BusinessLogic?
  var router: (NSObjectProtocol & SignIn19RoutingLogic & SignIn19DataPassing)?
  var doRememberMe: Bool = false
  override var preferredStatusBarStyle: UIStatusBarStyle{
        return .lightContent
    }
    
    @IBOutlet weak var navBarView: UIView!
    @IBOutlet weak var logoImageView: UIImageView!
    @IBOutlet weak var signInButton: UIButton!
    @IBOutlet weak var credentialsView: UIView!
    @IBOutlet weak var rememberMeBtn: UIButton!
    
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SignIn19Interactor()
    let presenter = SignIn19Presenter()
    let router = SignIn19Router()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    setupUI()
    doSomething()
  }
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.navigationBar.barStyle = .black
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = SignIn19.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: SignIn19.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
    func setupUI(){
    navBarView.backgroundColor = UIColor.appRed
    signInButton.backgroundColor = UIColor.appRed
    UIApplication.shared.statusBarView?.backgroundColor = UIColor.appStatusBarRed
     
    logoImageView.layer.cornerRadius = logoImageView.frame.width/2
        
    credentialsView.layer.shadowColor = UIColor.lightGray.cgColor
    credentialsView.layer.shadowOffset = CGSize(width: 1, height: 1)
    credentialsView.layer.shadowOpacity = 1.0
    }
    //MARK: IBAction
    
    @IBAction func rememberMeTapped(_ sender: Any) {
    doRememberMe.toggle()
    var imgName = ""
        if doRememberMe{
            imgName = "checked_box_app_background"
        }else{
            imgName = "unchecked_app_background"
        }
    rememberMeBtn.setImage(UIImage(named: imgName), for: .normal)
    }
    
}
