//
//  SignIn18ViewController.swift
//  LoginFlowApp
//
//  Created by Thanos on 06/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn18DisplayLogic: class
{
  func displaySomething(viewModel: SignIn18.Something.ViewModel)
}

class SignIn18ViewController: UIViewController, SignIn18DisplayLogic
{
  var interactor: SignIn18BusinessLogic?
  var router: (NSObjectProtocol & SignIn18RoutingLogic & SignIn18DataPassing)?

    @IBOutlet weak var navBarView: UIView!
    @IBOutlet weak var signInButton: UIButton!
    @IBOutlet weak var uploadImgButton: UIButton!
    @IBOutlet weak var credentialView: UIView!
    
    override var preferredStatusBarStyle: UIStatusBarStyle{
        return .lightContent
    }
    
    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SignIn18Interactor()
    let presenter = SignIn18Presenter()
    let router = SignIn18Router()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    setupUI()
    if self.revealViewController() != nil {
        self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
    }
    doSomething()
  }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.navigationBar.barStyle = .black
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = SignIn18.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: SignIn18.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
    // MARK:
    
    func setupUI(){
        UIApplication.shared.statusBarView?.backgroundColor = UIColor.appStatusBarRed
        
        signInButton.backgroundColor = UIColor.appRed
        uploadImgButton.layer.cornerRadius = uploadImgButton.frame.width/2
        navBarView.backgroundColor = UIColor.appRed
        
        credentialView.layer.shadowColor = UIColor.lightGray.cgColor
        credentialView.layer.shadowOffset = CGSize(width: 1, height: 1)
        credentialView.layer.shadowOpacity = 1
    }
}
