//
//  SignIn18Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 06/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn18BusinessLogic
{
  func doSomething(request: SignIn18.Something.Request)
}

protocol SignIn18DataStore
{
  //var name: String { get set }
}

class SignIn18Interactor: SignIn18BusinessLogic, SignIn18DataStore
{
  var presenter: SignIn18PresentationLogic?
  var worker: SignIn18Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignIn18.Something.Request)
  {
    worker = SignIn18Worker()
    worker?.doSomeWork()
    
    let response = SignIn18.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
