//
//  WelcomeGuest25ViewController.swift
//  LoginFlowApp
//
//  Created by Thanos on 08/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeGuest25DisplayLogic: class
{
  func displaySomething(viewModel: WelcomeGuest25.Something.ViewModel)
}

class WelcomeGuest25ViewController: UIViewController, WelcomeGuest25DisplayLogic
{
  var interactor: WelcomeGuest25BusinessLogic?
  var router: (NSObjectProtocol & WelcomeGuest25RoutingLogic & WelcomeGuest25DataPassing)?

    @IBOutlet weak var logoImageView: UIImageView!
    @IBOutlet weak var signInButton: UIButton!
    
    override var preferredStatusBarStyle: UIStatusBarStyle{
        return .lightContent
    }
    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = WelcomeGuest25Interactor()
    let presenter = WelcomeGuest25Presenter()
    let router = WelcomeGuest25Router()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    setupUI()
    if self.revealViewController() != nil {
        self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
    }
    doSomething()
  }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        self.navigationController?.navigationBar.barStyle = .black
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = WelcomeGuest25.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: WelcomeGuest25.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    func setupUI(){
        logoImageView.layer.cornerRadius = logoImageView.frame.width/2
        signInButton.backgroundColor = UIColor.appRed
    }
}
