//
//  WelcomeGuest25Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 08/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeGuest25PresentationLogic
{
  func presentSomething(response: WelcomeGuest25.Something.Response)
}

class WelcomeGuest25Presenter: WelcomeGuest25PresentationLogic
{
  weak var viewController: WelcomeGuest25DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: WelcomeGuest25.Something.Response)
  {
    let viewModel = WelcomeGuest25.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
