//
//  WelcomeGuest25Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 08/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeGuest25BusinessLogic
{
  func doSomething(request: WelcomeGuest25.Something.Request)
}

protocol WelcomeGuest25DataStore
{
  //var name: String { get set }
}

class WelcomeGuest25Interactor: WelcomeGuest25BusinessLogic, WelcomeGuest25DataStore
{
  var presenter: WelcomeGuest25PresentationLogic?
  var worker: WelcomeGuest25Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: WelcomeGuest25.Something.Request)
  {
    worker = WelcomeGuest25Worker()
    worker?.doSomeWork()
    
    let response = WelcomeGuest25.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
