//
//  SignIn_12Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 02/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn_12BusinessLogic
{
  func doSomething(request: SignIn_12.Something.Request)
}

protocol SignIn_12DataStore
{
  //var name: String { get set }
}

class SignIn_12Interactor: SignIn_12BusinessLogic, SignIn_12DataStore
{
  var presenter: SignIn_12PresentationLogic?
  var worker: SignIn_12Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignIn_12.Something.Request)
  {
    worker = SignIn_12Worker()
    worker?.doSomeWork()
    
    let response = SignIn_12.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
