//
//  SignIn_12Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 02/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn_12PresentationLogic
{
  func presentSomething(response: SignIn_12.Something.Response)
}

class SignIn_12Presenter: SignIn_12PresentationLogic
{
  weak var viewController: SignIn_12DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignIn_12.Something.Response)
  {
    let viewModel = SignIn_12.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
