//
//  SignIn_12Router.swift
//  LoginFlowApp
//
//  Created by Thanos on 02/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SignIn_12RoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SignIn_12DataPassing
{
  var dataStore: SignIn_12DataStore? { get }
}

class SignIn_12Router: NSObject, SignIn_12RoutingLogic, SignIn_12DataPassing
{
  weak var viewController: SignIn_12ViewController?
  var dataStore: SignIn_12DataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: SignIn_12ViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: SignIn_12DataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
