//
//  SignIn_12ViewController.swift
//  LoginFlowApp
//
//  Created by Thanos on 02/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn_12DisplayLogic: class
{
  func displaySomething(viewModel: SignIn_12.Something.ViewModel)
}

class SignIn_12ViewController: UIViewController, SignIn_12DisplayLogic
{
  var interactor: SignIn_12BusinessLogic?
  var router: (NSObjectProtocol & SignIn_12RoutingLogic & SignIn_12DataPassing)?
   
    override var preferredStatusBarStyle: UIStatusBarStyle{
        return .lightContent
    }
    var doRememberMe: Bool = false

    @IBOutlet weak var logoImageView: UIImageView!
    @IBOutlet weak var signInButton: UIButton!
    @IBOutlet weak var rememberMeBtn: UIButton!
    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SignIn_12Interactor()
    let presenter = SignIn_12Presenter()
    let router = SignIn_12Router()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    
    if self.revealViewController() != nil {
        self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
    }
    
    setupUI()
    doSomething()
  }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        self.navigationController?.navigationBar.barStyle = .black
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = SignIn_12.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: SignIn_12.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
    // MARK: View UI Setup
    
    func setupUI(){
        logoImageView.layer.cornerRadius = logoImageView.frame.width/2
        
        signInButton.backgroundColor = .appRed
        
        UIApplication.shared.statusBarView?.backgroundColor = UIColor.clear
    }
    
    // MARK: IBActions
    
    @IBAction func rememberMe(_ sender: Any) {
        doRememberMe.toggle()
        if doRememberMe{
            rememberMeBtn.setImage(UIImage(named: "checked_box"), for: .normal)
        }
        else{
            rememberMeBtn.setImage(UIImage(named: "unchecked_gray"), for: .normal)
        }
    }
    
}
