//
//  SignUp_9ViewController.swift
//  LoginFlowApp
//
//  Created by Thanos on 27/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_9DisplayLogic: class
{
  func displaySomething(viewModel: SignUp_9.Something.ViewModel)
}

class SignUp_9ViewController: UIViewController, SignUp_9DisplayLogic
{
  var interactor: SignUp_9BusinessLogic?
  var router: (NSObjectProtocol & SignUp_9RoutingLogic & SignUp_9DataPassing)?

    @IBOutlet weak var credentialView: UIView!
    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SignUp_9Interactor()
    let presenter = SignUp_9Presenter()
    let router = SignUp_9Router()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    setupUI()
    doSomething()
  }
  
    
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = SignUp_9.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: SignUp_9.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
    func setupUI(){
        credentialView.layer.shadowColor = UIColor.lightGray.cgColor
        credentialView.layer.shadowOffset = CGSize(width: 1, height: 1)
        credentialView.layer.shadowOpacity  = 1.0
    }
}
