//
//  ForgotPassword23Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 07/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPassword23PresentationLogic
{
  func presentSomething(response: ForgotPassword23.Something.Response)
}

class ForgotPassword23Presenter: ForgotPassword23PresentationLogic
{
  weak var viewController: ForgotPassword23DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ForgotPassword23.Something.Response)
  {
    let viewModel = ForgotPassword23.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
