//
//  ForgotPassword23ViewController.swift
//  LoginFlowApp
//
//  Created by Thanos on 07/01/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPassword23DisplayLogic: class
{
  func displaySomething(viewModel: ForgotPassword23.Something.ViewModel)
}

class ForgotPassword23ViewController: UIViewController, ForgotPassword23DisplayLogic
{
  var interactor: ForgotPassword23BusinessLogic?
  var router: (NSObjectProtocol & ForgotPassword23RoutingLogic & ForgotPassword23DataPassing)?

    override var preferredStatusBarStyle: UIStatusBarStyle{
        return .lightContent
    }
    
    @IBOutlet weak var resetPasswordBtn: UIButton!
    @IBOutlet weak var navBarView: UIView!
    
    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ForgotPassword23Interactor()
    let presenter = ForgotPassword23Presenter()
    let router = ForgotPassword23Router()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    setupUI()
    if self.revealViewController() != nil {
        self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
    }
    doSomething()
  }
  
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        self.navigationController?.navigationBar.barStyle = .black
    }
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = ForgotPassword23.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: ForgotPassword23.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
    func setupUI(){
        UIApplication.shared.statusBarView?.backgroundColor = UIColor.appStatusBarRed
        navBarView.backgroundColor = UIColor.appRed
        resetPasswordBtn.backgroundColor = UIColor.appRed
    }
}
