//
//  SignIn_7Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 23/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn_7BusinessLogic
{
  func doSomething(request: SignIn_7.Something.Request)
}

protocol SignIn_7DataStore
{
  //var name: String { get set }
}

class SignIn_7Interactor: SignIn_7BusinessLogic, SignIn_7DataStore
{
  var presenter: SignIn_7PresentationLogic?
  var worker: SignIn_7Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignIn_7.Something.Request)
  {
    worker = SignIn_7Worker()
    worker?.doSomeWork()
    
    let response = SignIn_7.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
