//
//  SignIn_7Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 23/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn_7PresentationLogic
{
  func presentSomething(response: SignIn_7.Something.Response)
}

class SignIn_7Presenter: SignIn_7PresentationLogic
{
  weak var viewController: SignIn_7DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignIn_7.Something.Response)
  {
    let viewModel = SignIn_7.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
