//
//  SignUp_4Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 21/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_4BusinessLogic
{
  func doSomething(request: SignUp_4.Something.Request)
}

protocol SignUp_4DataStore
{
  //var name: String { get set }
}

class SignUp_4Interactor: SignUp_4BusinessLogic, SignUp_4DataStore
{
  var presenter: SignUp_4PresentationLogic?
  var worker: SignUp_4Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignUp_4.Something.Request)
  {
    worker = SignUp_4Worker()
    worker?.doSomeWork()
    
    let response = SignUp_4.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
