//
//  SignUp_4Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 21/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUp_4PresentationLogic
{
  func presentSomething(response: SignUp_4.Something.Response)
}

class SignUp_4Presenter: SignUp_4PresentationLogic
{
  weak var viewController: SignUp_4DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignUp_4.Something.Response)
  {
    let viewModel = SignUp_4.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
