//
//  SignIn_4Interactor.swift
//  LoginFlowApp
//
//  Created by Thanos on 21/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn_4BusinessLogic
{
  func doSomething(request: SignIn_4.Something.Request)
}

protocol SignIn_4DataStore
{
  //var name: String { get set }
}

class SignIn_4Interactor: SignIn_4BusinessLogic, SignIn_4DataStore
{
  var presenter: SignIn_4PresentationLogic?
  var worker: SignIn_4Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignIn_4.Something.Request)
  {
    worker = SignIn_4Worker()
    worker?.doSomeWork()
    
    let response = SignIn_4.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
