//
//  SignIn_4Presenter.swift
//  LoginFlowApp
//
//  Created by Thanos on 21/12/19.
//  Copyright (c) 2019 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignIn_4PresentationLogic
{
  func presentSomething(response: SignIn_4.Something.Response)
}

class SignIn_4Presenter: SignIn_4PresentationLogic
{
  weak var viewController: SignIn_4DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignIn_4.Something.Response)
  {
    let viewModel = SignIn_4.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
